



formats <- list(
  tidyGWAS = list(
    CHR = "CHR",
    POS = "POS",
    RSID = "RSID",
    EffectAllele = "EffectAllele",
    OtherAllele = "OtherAllele",
    B = "B",
    OR = "OR",
    SE = "SE",
    Z = "Z",
    EAF = "EAF",
    P = "P",
    N = "N",
    CaseN = "CaseN",
    ControlN = "ControlN",
    EffectiveN =" EffectiveN",
    INFO = "INFO"
  ),
  SSF  = list(
    CHR = "chromosome",
    POS = "base_pair_location",
    RSID = "rsid",
    EffectAllele = "effect_allele",
    OtherAllele = "other_allele",
    B = "beta",
    SE = "standard_error",
    EAF = "effect_allele_frequency",
    P = "p_value",
    N = "n"
  ),

  REGENIE = list(
    CHR = "CHROM",
    POS = "GENPOS",
    RSID = "ID",
    EffectAllele = "ALLELE1",
    OtherAllele = "ALLELE0",
    EAF = "A1FREQ",
    B = "BETA",
    CaseN = "N_CASES",
    ControlN = "N_CONTROLS",
    INFO = "INFO",
    SE = "SE",
    N = "N"
  ),
  # source: https://yanglab.westlake.edu.cn/software/gcta/index.html#DataResource
  fastGWA = list(
    CHR = "CHR",
    POS = "POS",
    RSID = "SNP",
    EffectAllele = "A1",
    OtherAllele = "A2",
    EAF = "AF1",
    B = "BETA",
    N = "N",
    P = "P",
    SE = "SE"
  ),
  plink = list(
    POS = "BP",
    RSID = "SNP",
    EffectAllele = "A1",
    OtherAllele = "A2",
    EAF = "MAF",
    N = "NMISS"

  ),
  plink_glm = list(
    CHR = "#CHROM",
    RSID = "ID",
    EffectAllele = "A1",
    OtherAllele = "REF",
    EAF = "A1_FREQ",
    SE = "LOG(OR)_SE",
    Z = "Z_STAT",
    N = "OBS_CT"
  ),
  FINNGEN = list(
    CHR = "#chrom",
    POS = "pos",
    RSID = "rsids",
    EffectAllele = "alt",
    OtherAllele = "ref",
    EAF = "af_alt",
    P = "pval",
    B = "beta",
    SE = "sebeta",
    EAF = "af_alt"
  )

)

# copy-pasted from https://github.com/opain/GenoUtils/blob/main/R/constants.R
# all credit to Oliver Pain
colname_dict <- list(
  RSID = c(
    "SNP",
    "PREDICTOR",
    "SNPID",
    "MARKERNAME",
    "MARKER_NAME",
    "SNPTESTID",
    "ID_DBSNP49",
    "RSID",
    "ID",
    "RS_NUMBER",
    "MARKER",
    "RS",
    "RSNUMBER",
    "RS_NUMBERS",
    "SNP.NAME",
    "SNP ID",
    "SNP_ID",
    "LOCATIONALID",
    "ASSAY_NAME",
    "VARIANT_ID",
    "HM_RSID"
  ),
  EffectAllele = c(
    "A1",
    "ALLELE1",
    "ALLELE_1",
    "INC_ALLELE",
    "EA",
    "A1_EFFECT",
    "REF",
    "EFFECT_ALLELE",
    "RISK_ALLELE",
    "EFFECTALLELE",
    "EFFECT_ALL",
    "REFERENCE_ALLELE",
    "REF_ALLELE",
    "REFERENCEALLELE",
    "EA",
    "ALLELE_1",
    "INC_ALLELE",
    "ALLELE1",
    "A",
    "A_1",
    "CODED_ALLELE",
    "TESTED_ALLELE",
    "HM_EFFECT_ALLELE"
  ),
  OtherAllele = c(
    "A2",
    "ALLELE2",
    "ALLELE_2",
    "OTHER_ALLELE",
    "NON_EFFECT_ALLELE",
    "DEC_ALLELE",
    "OA",
    "NEA",
    "ALT",
    "A2_OTHER",
    "NONREF_ALLELE",
    "NEFFECT_ALLELE",
    "NEFFECTALLELE",
    "NONEFFECT_ALLELE",
    "OTHER_ALL",
    "OTHERALLELE",
    "NONEFFECTALLELE",
    "ALLELE0",
    "ALLELE_0",
    "ALT_ALLELE",
    "A_0",
    "NONCODED_ALLELE",
    "HM_OTHER_ALLELE"
  ),
  B = c(
    "BETA",
    "B",
    "EFFECT_BETA",
    "EFFECT",
    "EFFECTS",
    "SIGNED_SUMSTAT",
    "EST",
    "GWAS_BETA",
    "EFFECT_A1",
    "EFFECTA1",
    "EFFECT_NW",
    "HM_BETA",
    "LOG_ODDS"
  ),
  OR = c(
    "OR",
    "ODDS-RATIO",
    "ODDS_RATIO",
    "ODDSRATIO",
    "OR(MINALLELE)",
    "OR.LOGISTIC",
    "OR_RAN",
    "OR(A1)",
    "HM_ODDS_RATIO"
  ),
  SE = c(
    "SE",
    "STDER",
    "STDERR",
    "STD",
    "STANDARD_ERROR",
    "OR_SE",
    "STANDARDERROR",
    "STDERR_NW",
    "META.SE",
    "SE_DGC",
    "SE.2GC"
  ),
  Z = c(
    "Z",
    "ZSCORE",
    "Z-SCORE",
    "ZSTAT",
    "ZSTATISTIC",
    "GC_ZSCORE",
    "BETAZSCALE"
  ),
  INFO = c(
    "INFO",
    "IMPINFO",
    "IMPQUALITY",
    "INFO.PLINK",
    "INFO_UKBB",
    "INFO_UKB"
  ),
  P = c(
    "P",
    "PVALUE",
    "PVAL",
    "P_VALUE",
    "GC_PVALUE",
    "WALD_P",
    "P.VAL",
    "GWAS_P",
    "P-VALUE",
    "P-VAL",
    "FREQUENTIST_ADD_PVALUE",
    "P.VALUE",
    "P_VAL",
    "SCAN-P",
    "P.LMM",
    "META.PVAL",
    "P_RAN",
    "P.ADD",
    "P_BOLT_LMM"
  ),
  N = c(
    "N",
    "WEIGHT",
    "NCOMPLETESAMPLES",
    "TOTALSAMPLESIZE",
    "TOTALN",
    "TOTAL_N",
    "N_COMPLETE_SAMPLES",
    "N_TOTAL",
    "N_SAMPLES",
    "N_ANALYZED",
    "NSAMPLES",
    "SAMPLESIZE",
    "SAMPLE_SIZE",
    "TOTAL_SAMPLE_SIZE",
    "TOTALSAMPLESIZE",
    "N_TOTAL_SUM",
    "OBS_CT"
  ),
  CaseN = c(
    "N_CAS",
    "NCASE",
    "N_CASE",
    "N_CASES",
    "NCAS",
    "NCA",
    "NCASES",
    "CASES",
    "CASES_N"
  ),
  ControlN = c(
    "N_CON",
    "NCONTROL",
    "N_CONTROL",
    "N_CONTROLS",
    "NCON",
    "NCO",
    "N_CON",
    "NCONTROLS",
    "CONTROLS",
    "CONTROLS_N"
  ),
    EffectiveN = c(
         "NEF",
         "NEFF",
         "NEFFECTIVE",
         "NE"
     ),
  EAF = c(
    "FRQ",
    "FREQ",
    "MAF",
    "AF",
    "CEUAF",
    "FREQ1",
    "EAF",
    "FREQ1.HAPMAP",
    "FREQALLELE1HAPMAPCEU",
    "FREQ.ALLELE1.HAPMAPCEU",
    "EFFECT_ALLELE_FREQ",
    "FREQ.A1",
    "MA_FREQ",
    "MAF_NW",
    "FREQ_A1",
    "A1FREQ",
    "CODED_ALLELE_FREQUENCY",
    "FREQ_TESTED_ALLELE_IN_HRS",
    "EAF_HRC",
    "EAF_UKB",
    "EFFECT_ALLELE_FREQUENCY",
    "HM_EFFECT_ALLELE_FREQUENCY",
    "A1_FREQ"
  ),
  # FRQ_A = c(
  #   "FRQ_A",
  #   "FREQ_A",
  #   "F_A"
  # ),
  # FRQ_U = c(
  #   "FRQ_U",
  #   "FREQ_U",
  #   "F_U"
  # ),
  CHR = c(
    "#CHR",
    "#CHROM",
    "CHR",
    "CH",
    "CHROMOSOME",
    "CHROM",
    "CHR_BUILD38",
    "CHR_BUILD37",
    "CHR_BUILD36",
    "CHR_B38",
    "CHR_B37",
    "CHR_B36",
    "CHR_ID",
    "SCAFFOLD",
    "HG19CHR",
    "CHR.HG19",
    "CHR_HG19",
    "HG18CHR",
    "CHR.HG18",
    "CHR_HG18",
    "CHR_BP_HG19B37",
    "HG19CHRC",
    "HM_CHROM"
  ),
  POS = c(
    "ORIGBP",
    "BP",
    "POS",
    "POSITION",
    "LOCATION",
    "PHYSPOS",
    "GENPOS",
    "CHR_POSITION",
    "POS_B38",
    "POS_BUILD38",
    "POS_B37",
    "POS_BUILD37",
    "BP_HG19B37",
    "POS_B36",
    "POS_BUILD36",
    "POS.HG19",
    "POS.HG18",
    "POS_HG19",
    "POS_HG18",
    "BP_HG19",
    "BP_HG18",
    "BP.GRCH38",
    "BP.GRCH37",
    "POSITION(HG19)",
    "POSITION(HG18)",
    "POS(B38)",
    "POS(B37)",
    "BASE_PAIR_LOCATION",
    "HM_POS"
  )
)
